# 系统配置
system:
  # 运行模式，支持 debug、release，建议开发时使用 debug，生产时使用 release
  mode: debug
  # 监听配置
  listen:
    # 监听地址，服务绑定 IP 地址，服务启动时可以使用 --host 参数覆盖该值
    host: 0.0.0.0
    # 监听端口，推荐使用 3000-65535 之间的端口，服务启动时可以使用 --port 参数覆盖该值
    port: 12345
  # 节点角色说明（一个集群中每个角色至少要有一个节点设置为 true）：
  # 1. role-leader：允许竞选 Leader，Leader 节点负责同步任务到任务通道，如果没有 Leader，则没有任务提供给 Worker 节点执行
  # 2. role-worker：允许成为 Worker，Worker 节点负责执行任务通道中的任务
  # 3. role-web：Web 后端服务角色，为前端服务提供后端接口支持，否则前端服务无法正常工作
  role:
    # 是否允许竞选 Leader，服务启动时可以使用 --role-leader 参数指定是否开启
    leader: true
    # 是否允许成为 Worker，服务启动时可以使用 --role-worker 参数指定是否开启
    worker: true
    # 是否是 WebServer 角色，服务启动时可以使用 --role-web 参数指定是否开启
    web: true

# 日志配置
log:
  system:
    # 是否开启系统日志，可选值：true、false
    enabled: true
    # 日志级别，可选值：debug、info、warn、error、panic、fatal
    level: info
    # 日志输出格式，可选值：json、text
    formatter: text
    # 日志输出目录
    path: logs
    # 日志文件前缀
    prefix: system
    # 是否切割
    rolling:
      # 是否开启切割
      enabled: true
      # 日志文件最大大小，单位：MB
      max_size: 100
      # 日志文件最大数量
      max_backups: 10
      # 日志文件最大保留天数
      max_age: 30
      # 是否压缩
      compress: true
  access:
    # 是否开启访问日志，可选值：true、false
    enabled: true
    # 日志级别，可选值：debug、info、warn、error、panic、fatal
    level: info
    # 日志输出格式，可选值：json、text
    formatter: json
    # 日志输出目录
    path: logs
    # 日志文件前缀
    prefix: access
    # 是否切割
    rolling:
      # 是否开启切割
      enabled: true
      # 日志文件最大大小，单位：MB
      max_size: 100
      # 日志文件最大数量
      max_backups: 10
      # 日志文件最大保留天数
      max_age: 30
      # 是否压缩
      compress: true

